<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/21 14:57:22
sfConfig::add(array(
  'app_orangehrm_core_leave_plugin_default_work_shift_length_hours' => 8,
  'app_items_per_page' => 50,
  'app_sort_asc_class' => 'ASC',
  'app_sort_desc_class' => 'DESC',
  'app_sort_default_class' => 'null',
));
